name: vpn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  getwidget: ^7.0.0
  go_router: ^17.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
